### ISSUE TITLE
Add buy & sell points [Feature Suggestion]

### ISSUE THREAD

**Issue by smjure** [iamjinlei/go-tachart#2]
First of all, thank you for this awesome package.

It would be very useful if buy & sell points could be added into the `tachart.AddOverlay()`, e.g.  a single entry and exit points `tachart.NewBuy()` and `tachart.NewSell()` or even the pair `tachart.NewBuySell()`. 

![2021-11-03_14-18](https://user-images.githubusercontent.com/22912191/140067247-eafab5bd-c534-404b-86e8-0c68303181d5.png)

**Comment by iamjinlei** [comment]
You can use "events" for this purpose. Note the small colorful boxes right above the time axis. The example in the README shows how to add events.
