### ISSUE TITLE
Multiple events per candle

### ISSUE THREAD

**Issue by smjure** [iamjinlei/go-tachart#4]
Following up #2, is there possibility to display two events per candle? For example, it's very common to have Earnings report day and position entry on the same day. At the moment only the last Event is showen in the tachart, but not both.

**Comment by iamjinlei** [comment]
This is currently not supported. It is gonna be tricky to have a good layout for multiple event tags on the same slot

**Comment by smjure** [comment]
Perhaps the idea from #2 should be reconsidered, i.e. to put optioinally a scatter chart as `tachart.AddOverlay()` with e.g. `^` and `v` markers and leave the Events untouched. Advantage of this would be also that entry and exit points would be exactly pinpointed in the chart.
